# Generated by Django 6.0.6 on 2026-06-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_featured',
        ),
    ]
